### ISSUE TITLE
possibility to pass a string to the header option

### ISSUE THREAD

**Issue by omarkhd** [AirAsiaExpedia/node-simple-xml#4]
I need to send a simple header but with some attributes, and the node-simple-xml module cannot handle serializing attributes on the xml nodes, a simple header string could fix it

**Comment by omarkhd** [comment]
I've submitted a pull request for this

**Comment by jtblin** [comment]
Thanks, LGTM just had a comment. What is the object that cannot be serialized out of curiosity? I'd like to improve `simple-xml` as well.

**Comment by jtblin** [comment]
PR closed in `node-foam`. What is the object that cannot be serialized out of curiosity?

**Comment by omarkhd** [comment]
I needed to put this header in the SOAP request:
```
<ApiAuthentication xmlns="http://api.qwerty.org">
   <LoginName>qwerty</LoginName>
   <Password>qwerty</Password>
   <Company>qwerty</Company>
</ApiAuthentication>
```
But as I read the ```simple-xml``` code, it does not support attributes when stringifying.
